version: '3.8'
services:
  nginx:
    build: 
      context: .
    ports:
      - 3000:80
    volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    #   - ./html:/usr/share/nginx/html
      - ./build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf