version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=category
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql-db:/data/db

  nodejs-app:
    build: .
    restart: unless-stopped
    environment: #connect to outside localhost
      - DB_HOST=host.docker.internal
      #-DB_HOST=mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    #   - ./html:/usr/share/nginx/html
      - ../frontend/build:/usr/share/nginx/html
      - ../frontend/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  mysql-db:
 